export const GET_MOVIECOUNT_REQUEST = 'GET_MOVIECOUNT_REQUEST'
export const GET_MOVIECOUNT_SUCCESS = 'GET_MOVIECOUNT_SUCCESS' 
export const GET_MOVIECOUNT_FAILURE = 'GET_MOVIECOUNT_FAILURE'  

export const GET_CUSTOMERCOUNT_REQUEST = 'GET_CUSTOMERCOUNT_REQUEST'
export const GET_CUSTOMERCOUNT_SUCCESS = 'GET_CUSTOMERCOUNT_SUCCESS' 
export const GET_CUSTOMERCOUNT_FAILURE = 'GET_CUSTOMERCOUNT_FAILURE'  

export const GET_RENTALSCOUNT_REQUEST = 'GET_RENTALSCOUNT_REQUEST'
export const GET_RENTALSCOUNT_SUCCESS = 'GET_RENTALSCOUNT_SUCCESS' 
export const GET_RENTALSCOUNT_FAILURE = 'GET_RENTALSCOUNT_FAILURE'  