export const POST_CLOSERENTAL_REQUEST = 'POST_CLOSERENTAL_REQUEST'
export const POST_CLOSERENTAL_SUCCESS = 'POST_CLOSERENTAL_SUCCESS' 
export const POST_CLOSERENTAL_FAILURE = 'POST_CLOSERENTAL_FAILURE'  

export const POST_CLOSEDRENTAL_REQUEST = 'POST_CLOSEDRENTAL_REQUEST'
export const POST_CLOSEDRENTAL_SUCCESS = 'POST_CLOSEDRENTAL_SUCCESS' 
export const POST_CLOSEDRENTAL_FAILURE = 'POST_CLOSEDRENTAL_FAILURE'  