export const FETCH_RENTAL_REQUEST = 'FETCH_RENTAL_REQUEST'
export const FETCH_RENTAL_SUCCESS = 'FETCH_RENTAL_SUCCESS' 
export const FETCH_RENTAL_FAILURE = 'FETCH_RENTAL_FAILURE'

export const POST_RENTAL_REQUEST = 'POST_RENTAL_REQUEST'
export const POST_RENTAL_SUCCESS = 'POST_RENTAL_SUCCESS' 
export const POST_RENTAL_FAILURE = 'POST_RENTAL_FAILURE'  

export const EDIT_RENTAL_REQUEST = 'EDIT_RENTAL_REQUEST'
export const EDIT_RENTAL_SUCCESS = 'EDIT_RENTAL_SUCCESS' 
export const EDIT_RENTAL_FAILURE = 'EDIT_RENTAL_FAILURE'  

export const DELETE_RENTAL_REQUEST = 'DELETE_RENTAL_REQUEST'
export const DELETE_RENTAL_SUCCESS = 'DELETE_RENTAL_SUCCESS' 
export const DELETE_RENTAL_FAILURE = 'DELETE_RENTAL_FAILURE'  

export const GETSINGLE_RENTAL_REQUEST = 'GETSINGLE_RENTAL_REQUEST'
export const GETSINGLE_RENTAL_SUCCESS = 'GETSINGLE_RENTAL_SUCCESS' 
export const GETSINGLE_RENTAL_FAILURE = 'GETSINGLE_RENTAL_FAILURE'