export const FETCH_LOGINAUTH_REQUEST = 'FETCH_LOGINAUTH_REQUEST'
export const FETCH_LOGINAUTH_SUCCESS = 'FETCH_LOGINAUTH_SUCCESS' 
export const FETCH_LOGINAUTH_FAILURE = 'FETCH_LOGINAUTH_FAILURE'

export const FETCH_LOGOUTAUTH_REQUEST = 'FETCH_LOGOUTAUTH_REQUEST'
export const FETCH_LOGOUTAUTH_SUCCESS = 'FETCH_LOGOUTAUTH_SUCCESS' 
export const FETCH_LOGOUTAUTH_FAILURE = 'FETCH_LOGOUTAUTH_FAILURE'