
export const FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST'
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS' 
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE'

export const POST_CUSTOMER_REQUEST = 'POST_CUSTOMER_REQUEST'
export const POST_CUSTOMER_SUCCESS = 'POST_CUSTOMER_SUCCESS' 
export const POST_CUSTOMER_FAILURE = 'POST_CUSTOMER_FAILURE'  

export const EDIT_CUSTOMER_REQUEST = 'EDIT_CUSTOMER_REQUEST'
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS' 
export const EDIT_CUSTOMER_FAILURE = 'EDIT_CUSTOMER_FAILURE'  