
export const FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST'
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS' 
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE'

export const POST_CUSTOMER_REQUEST = 'POST_CUSTOMER_REQUEST'
export const POST_CUSTOMER_SUCCESS = 'POST_CUSTOMER_SUCCESS' 
export const POST_CUSTOMER_FAILURE = 'POST_CUSTOMER_FAILURE'  

export const EDIT_CUSTOMER_REQUEST = 'EDIT_CUSTOMER_REQUEST'
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS' 
export const EDIT_CUSTOMER_FAILURE = 'EDIT_CUSTOMER_FAILURE'  

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS' 
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE'  

export const GETSINGLE_CUSTOMER_REQUEST = 'GETSINGLE_CUSTOMER_REQUEST'
export const GETSINGLE_CUSTOMER_SUCCESS = 'GETSINGLE_CUSTOMER_SUCCESS' 
export const GETSINGLE_CUSTOMER_FAILURE = 'GETSINGLE_CUSTOMER_FAILURE'  