export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST'
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS' 
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE'

export const POST_MOVIE_REQUEST = 'POST_MOVIE_REQUEST'
export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS' 
export const POST_MOVIE_FAILURE = 'POST_MOVIE_FAILURE'  

export const EDIT_MOVIE_REQUEST = 'EDIT_MOVIE_REQUEST'
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS' 
export const EDIT_MOVIE_FAILURE = 'EDIT_MOVIE_FAILURE'  

export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST'
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS' 
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE'  

export const GETSINGLE_MOVIE_REQUEST = 'GETSINGLE_MOVIE_REQUEST'
export const GETSINGLE_MOVIE_SUCCESS = 'GETSINGLE_MOVIE_SUCCESS' 
export const GETSINGLE_MOVIE_FAILURE = 'GETSINGLE_MOVIE_FAILURE'