export const FETCH_GENRE_REQUEST = 'FETCH_GENRE_REQUEST'
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS' 
export const FETCH_GENRE_FAILURE = 'FETCH_GENRE_FAILURE'

export const POST_GENRE_REQUEST = 'POST_GENRE_REQUEST'
export const POST_GENRE_SUCCESS = 'POST_GENRE_SUCCESS' 
export const POST_GENRE_FAILURE = 'POST_GENRE_FAILURE'  

export const EDIT_GENRE_REQUEST = 'EDIT_GENRE_REQUEST'
export const EDIT_GENRE_SUCCESS = 'EDIT_GENRE_SUCCESS' 
export const EDIT_GENRE_FAILURE = 'EDIT_GENRE_FAILURE'  

export const DELETE_GENRE_REQUEST = 'DELETE_GENRE_REQUEST'
export const DELETE_GENRE_SUCCESS = 'DELETE_GENRE_SUCCESS' 
export const DELETE_GENRE_FAILURE = 'DELETE_GENRE_FAILURE'  

export const GETSINGLE_GENRE_REQUEST = 'GETSINGLE_GENRE_REQUEST'
export const GETSINGLE_GENRE_SUCCESS = 'GETSINGLE_GENRE_SUCCESS' 
export const GETSINGLE_GENRE_FAILURE = 'GETSINGLE_GENRE_FAILURE'